;;; check-ime.el --- Buffer preedit regression checks -*- lexical-binding: t; -*-
(require 'cl-lib)
(add-to-list 'load-path (file-name-directory load-file-name))
(require 'neo-ime)

(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (buffer-enable-undo)
  (insert "before after")
  (goto-char 8)
  (set-buffer-modified-p nil)
  (let ((undo buffer-undo-list))
    (neo-ime--display (selected-window) "にほんご" 2 [0 0 1 1])
    (cl-assert (equal (buffer-substring-no-properties (point-min) (point-max)) "before にほんごafter"))
    (cl-assert (= (point) 10))
    (cl-assert (not (buffer-modified-p)))
    (cl-assert (equal undo buffer-undo-list))
    (cl-assert (eq (get-text-property 10 'face) 'neo-ime-target))
    (cl-assert (eq (face-attribute 'neo-ime-preedit :background) 'unspecified))
    ;; Cursor-only updates must not replace the underlying characters.
    (let ((tick (buffer-chars-modified-tick)))
      (neo-ime--display (selected-window) "にほんご" 1 [0 0 1 1])
      (cl-assert (= tick (buffer-chars-modified-tick))))
    (neo-ime--display (selected-window) "日本語" 3 [1 1 0])
    (cl-assert (equal (buffer-substring-no-properties (point-min) (point-max)) "before 日本語after"))
    (cl-assert (equal undo buffer-undo-list))
    (neo-ime--clear)
    (cl-assert (equal (buffer-string) "before after"))
    (cl-assert (= (point) 8))
    (cl-assert (not (buffer-modified-p)))
    (cl-assert (equal undo buffer-undo-list))))

(cl-assert (= (neo-ime--character-offset "あ😀い" 3) 2))
(cl-assert (= (neo-ime--character-offset "あ😀い" 99) 3))
(cl-assert (= (neo-ime--character-offset "あ😀い" -1) 0))
(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (neo-ime--display (selected-window) "あ😀い" 3 [0 1 1 0])
  (cl-assert (= (point) 3))
  (cl-assert (eq (get-text-property 2 'face) 'neo-ime-target))
  (neo-ime--clear))

;; Confirmed text alone must survive and form a real Undo/Redo edit.
(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (buffer-enable-undo)
  (insert "prefix:")
  (setq buffer-undo-list nil)
  (set-buffer-modified-p nil)
  (let ((cancelled nil)
        (neo-ime--frames (list (cons (selected-frame) 10))))
    (cl-letf (((symbol-function 'neo-ime-native-cancel)
               (lambda (_) (setq cancelled t))))
      (neo-ime--display (selected-window) "にほん" 2 [0 0 0])
      (let ((this-command 'self-insert-command) (last-command-event ?日))
        (neo-ime--before-command)
        (self-insert-command 1))
      (let ((this-command 'self-insert-command) (last-command-event ?本))
        (neo-ime--before-command)
        (self-insert-command 1))
      (cl-assert (not cancelled))
      (cl-assert (equal (buffer-string) "prefix:日本"))
      (cl-assert (buffer-modified-p))
      (undo-boundary)
      (undo-only 1)
      (cl-assert (equal (buffer-string) "prefix:"))
      (cl-assert (not (buffer-modified-p)))
      (let ((last-command 'undo)) (undo-redo 1))
      (cl-assert (equal (buffer-string) "prefix:日本"))
      ;; Partial commit followed by a new clause, then cancel/save.
      (neo-ime--display (selected-window) "語" 1 [0])
      (with-temp-buffer (neo-ime--before-save))
      (cl-assert cancelled)
      (cl-assert (equal (buffer-string) "prefix:日本")))))

(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (insert "modified")
  (neo-ime--display (selected-window) "次" 0 [0])
  (neo-ime--clear)
  (cl-assert (buffer-modified-p)))

;; Cleanup must work even when a buffer becomes read-only during composition.
(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (neo-ime--display (selected-window) "次" 0 [0])
  (setq buffer-read-only t)
  (neo-ime--clear)
  (cl-assert (equal (buffer-string) "")))
(princ "NEO_IME_EL=PASS buffer-preedit undo-redo cancel modified utf16 stable-text\n")
