;;; check-ime-gui.el --- Real GUI/module lifecycle -*- lexical-binding: t; -*-
;; Run in a separate GUI Emacs: emacs -Q -l check-ime-gui.el
(require 'cl-lib)
(require 'package)
(defvar neo-ime-candidate-backend)
(defconst neo-ime-check-root (file-name-directory load-file-name))
(setq native-comp-jit-compilation nil)
(defun neo-ime-gui-check ()
 (let* ((user-emacs-directory (make-temp-file "neo-ime-install-" t))
       (package-user-dir (expand-file-name "elpa" user-emacs-directory))
       (package-archives nil)
       (package-check-signature nil)
       (frame nil))
  (unwind-protect
      (progn
        (package-initialize)
        (package-install-file (expand-file-name "var/neo-ime-0.1.4.tar" neo-ime-check-root))
        (require 'neo-ime)
        (cl-assert (file-in-directory-p (locate-library "neo-ime") package-user-dir))
        (cl-assert (file-exists-p neo-ime-native-file))
        (setq frame (make-frame '((window-system . w32) (visibility . nil))))
        (select-frame frame)
        (neo-ime-mode 1)
        (cl-assert (featurep 'neo-ime-native))
        (cl-assert (assq frame neo-ime--frames))
        (let ((snapshot (neo-ime-native-snapshot (neo-ime--hwnd frame))))
          (cl-assert (equal (aref snapshot 1) ""))
          (cl-assert (not (aref snapshot 4))))
        (neo-ime-native-cancel (neo-ime--hwnd frame))
        (neo-ime--poll)
        ;; Synthetic rendering snapshots must not race live native polling.
        (cancel-timer neo-ime--timer)
        (setq neo-ime--timer nil)
        (neo-ime--display (frame-selected-window frame) "亜" 1 [1])
        (redisplay t)
        (neo-ime--show-candidates frame [1 "亜" 1 [1] t ["あ" "亜" "😀"] 1 0 100])
        (cl-assert (frame-live-p neo-ime--candidate-frame))
        (cl-assert (not (assq neo-ime--candidate-frame neo-ime--frames)))
        (cl-assert (frame-parameter neo-ime--candidate-frame 'no-accept-focus))
        (let ((popup neo-ime--candidate-frame))
          (neo-ime--show-candidates frame [2 "亜" 1 [1] t ["あ" "亜" "😀"] 2 0 100])
          (cl-assert (eq popup neo-ime--candidate-frame)))
        (neo-ime--clear)
        (cl-assert (not (frame-visible-p neo-ime--candidate-frame)))
        ;; Optional real Corfu renderer check: add Corfu/compat to load-path
        ;; and set NEO_IME_CHECK_CORFU=1; no mandatory package dependency.
        (when (getenv "NEO_IME_CHECK_CORFU")
          (require 'corfu)
          (make-frame-visible frame)
          (let ((neo-ime-candidate-backend 'corfu))
            (with-current-buffer (window-buffer (frame-selected-window frame))
              (corfu-mode 1)
              (insert "a")
              (completion-in-region (1- (point)) (point) '("abc" "abd"))
              (cl-assert completion-in-region-mode))
            (neo-ime--display (frame-selected-window frame) "亜" 1 [1])
            (cl-assert (not completion-in-region-mode))
            (redisplay t)
            (neo-ime--show-candidates frame [3 "亜" 1 [1] t ["あ" "亜" "😀"] 1 0 100])
            (redisplay t)
            (cl-assert neo-ime--corfu-visible)
            (cl-assert (frame-live-p (symbol-value 'corfu--frame)))
            (cl-assert (frame-visible-p (symbol-value 'corfu--frame)))
            (cl-assert (not (assq (symbol-value 'corfu--frame) neo-ime--frames)))
            (cl-assert (not (frame-visible-p neo-ime--candidate-frame)))
            (with-current-buffer " *corfu*"
              (cl-assert (string-match-p "2  亜" (buffer-string)))
              (goto-char (point-min)) (forward-line 1)
              (let ((face (get-text-property (point) 'face)))
                (cl-assert (or (eq face 'corfu-current)
                               (and (listp face) (memq 'corfu-current face))))))
            (neo-ime--clear)
            (sit-for 0.2)
            (with-current-buffer (window-buffer (frame-selected-window frame))
              (corfu-mode -1))
            (cl-assert (not neo-ime--corfu-visible))
            (cl-assert (not (frame-visible-p (symbol-value 'corfu--frame))))))
        (neo-ime-mode 1)
        (cl-assert (= (length neo-ime--frames)
                      (length (cl-remove-if-not
                               (lambda (f) (and (eq (window-system f) 'w32)
                                                (not (frame-parent f)))) (frame-list)))))
        (neo-ime-mode -1)
        (cl-assert (not neo-ime--frames))
        (cl-assert (not neo-ime--timer))
        (cl-assert (not neo-ime--candidate-frame))
        (cl-assert (not (neo-ime-native-snapshot (neo-ime--hwnd frame))))
        (neo-ime-mode 1)
        (let ((second (make-frame '((window-system . w32) (visibility . nil)))))
          (cl-assert (assq second neo-ime--frames))
          (delete-frame second t)
          (cl-assert (not (assq second neo-ime--frames))))
        (neo-ime-mode -1)
        (with-temp-file (expand-file-name "var/check-ime-gui.log" neo-ime-check-root)
          (insert (format "NEO_IME_GUI=PASS clean-package-install real-w32-frames enable-disable-reenable corfu=%s\n"
                          (if (getenv "NEO_IME_CHECK_CORFU") "tested" "skipped")))))
    (when (fboundp 'neo-ime-mode) (neo-ime-mode -1))
    (when (frame-live-p frame) (delete-frame frame t)))))

(condition-case error-data
    (progn
      (modify-frame-parameters nil '((visibility . nil)))
      (neo-ime-gui-check)
      (kill-emacs 0))
  (error
   (with-temp-file (expand-file-name "var/check-ime-gui.log" neo-ime-check-root)
     (insert (format "NEO_IME_GUI=FAIL %S\n" error-data)))
   (kill-emacs 1)))
