;;; check-ime-gui.el --- Real GUI/module lifecycle -*- lexical-binding: t; -*-
;; Run in a separate GUI Emacs: emacs -Q -l check-ime-gui.el
(require 'cl-lib)
(require 'package)
(defconst neo-ime-check-root (file-name-directory load-file-name))
(setq native-comp-jit-compilation nil)
(defun neo-ime-gui-check ()
 (let* ((user-emacs-directory (make-temp-file "neo-ime-install-" t))
       (package-user-dir (expand-file-name "elpa" user-emacs-directory))
       (package-archives nil)
       (package-check-signature nil)
       (frame nil))
  (unwind-protect
      (progn
        (package-initialize)
        (package-install-file (expand-file-name "var/neo-ime-0.1.0.tar" neo-ime-check-root))
        (require 'neo-ime)
        (cl-assert (file-in-directory-p (locate-library "neo-ime") package-user-dir))
        (cl-assert (file-exists-p neo-ime-native-file))
        (setq frame (make-frame '((window-system . w32) (visibility . nil))))
        (select-frame frame)
        (neo-ime-mode 1)
        (cl-assert (featurep 'neo-ime-native))
        (cl-assert (assq frame neo-ime--frames))
        (let ((snapshot (neo-ime-native-snapshot (neo-ime--hwnd frame))))
          (cl-assert (equal (aref snapshot 1) ""))
          (cl-assert (not (aref snapshot 4))))
        (neo-ime-native-cancel (neo-ime--hwnd frame))
        (neo-ime--poll)
        (neo-ime-mode 1)
        (cl-assert (= (length neo-ime--frames)
                      (length (cl-remove-if-not
                               (lambda (f) (eq (window-system f) 'w32)) (frame-list)))))
        (neo-ime-mode -1)
        (cl-assert (not neo-ime--frames))
        (cl-assert (not neo-ime--timer))
        (cl-assert (not (neo-ime-native-snapshot (neo-ime--hwnd frame))))
        (neo-ime-mode 1)
        (let ((second (make-frame '((window-system . w32) (visibility . nil)))))
          (cl-assert (assq second neo-ime--frames))
          (delete-frame second t)
          (cl-assert (not (assq second neo-ime--frames))))
        (neo-ime-mode -1)
        (with-temp-file (expand-file-name "var/check-ime-gui.log" neo-ime-check-root)
          (insert "NEO_IME_GUI=PASS clean-package-install real-w32-frames enable-disable-reenable\n")))
    (when (fboundp 'neo-ime-mode) (neo-ime-mode -1))
    (when (frame-live-p frame) (delete-frame frame t)))))

(condition-case error-data
    (progn
      (modify-frame-parameters nil '((visibility . nil)))
      (neo-ime-gui-check)
      (kill-emacs 0))
  (error
   (with-temp-file (expand-file-name "var/check-ime-gui.log" neo-ime-check-root)
     (insert (format "NEO_IME_GUI=FAIL %S\n" error-data)))
   (kill-emacs 1)))
