;;; check-ime.el --- Buffer preedit regression checks -*- lexical-binding: t; -*-
(require 'cl-lib)
(add-to-list 'load-path (file-name-directory load-file-name))
(require 'neo-ime)

(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (buffer-enable-undo)
  (insert "before after")
  (goto-char 8)
  (set-buffer-modified-p nil)
  (let ((undo buffer-undo-list))
    (neo-ime--display (selected-window) "にほんご" 2 [0 0 1 1])
    (cl-assert (equal (buffer-substring-no-properties (point-min) (point-max)) "before にほんごafter"))
    (cl-assert (= (point) 10))
    (cl-assert (not (buffer-modified-p)))
    (cl-assert (equal undo buffer-undo-list))
    (cl-assert (eq (get-text-property 10 'face) 'neo-ime-target))
    (cl-assert (eq (face-attribute 'neo-ime-preedit :background) 'unspecified))
    ;; Cursor-only updates must not replace the underlying characters.
    (let ((tick (buffer-chars-modified-tick)))
      (neo-ime--display (selected-window) "にほんご" 1 [0 0 1 1])
      (cl-assert (= tick (buffer-chars-modified-tick))))
    (neo-ime--display (selected-window) "日本語" 3 [1 1 0])
    (cl-assert (equal (buffer-substring-no-properties (point-min) (point-max)) "before 日本語after"))
    (cl-assert (equal undo buffer-undo-list))
    (neo-ime--clear)
    (cl-assert (equal (buffer-string) "before after"))
    (cl-assert (= (point) 8))
    (cl-assert (not (buffer-modified-p)))
    (cl-assert (equal undo buffer-undo-list))))

(cl-assert (= (neo-ime--character-offset "あ😀い" 3) 2))
(cl-assert (= (neo-ime--character-offset "あ😀い" 99) 3))
(cl-assert (= (neo-ime--character-offset "あ😀い" -1) 0))
(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (neo-ime--display (selected-window) "あ😀い" 3 [0 1 1 0])
  (cl-assert (= (point) 3))
  (cl-assert (eq (get-text-property 2 'face) 'neo-ime-target))
  (neo-ime--clear))

;; Confirmed text alone must survive and form a real Undo/Redo edit.
(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (buffer-enable-undo)
  (insert "prefix:")
  (setq buffer-undo-list nil)
  (set-buffer-modified-p nil)
  (let ((cancelled nil)
        (neo-ime--frames (list (cons (selected-frame) 10))))
    (cl-letf (((symbol-function 'neo-ime-native-cancel)
               (lambda (_) (setq cancelled t))))
      (neo-ime--display (selected-window) "にほん" 2 [0 0 0])
      (let ((this-command 'self-insert-command) (last-command-event ?日))
        (neo-ime--before-command)
        (self-insert-command 1))
      (let ((this-command 'self-insert-command) (last-command-event ?本))
        (neo-ime--before-command)
        (self-insert-command 1))
      (cl-assert (not cancelled))
      (cl-assert (equal (buffer-string) "prefix:日本"))
      (cl-assert (buffer-modified-p))
      (undo-boundary)
      (undo-only 1)
      (cl-assert (equal (buffer-string) "prefix:"))
      (cl-assert (not (buffer-modified-p)))
      (let ((last-command 'undo)) (undo-redo 1))
      (cl-assert (equal (buffer-string) "prefix:日本"))
      ;; Partial commit followed by a new clause, then cancel/save.
      (neo-ime--display (selected-window) "語" 1 [0])
      (with-temp-buffer (neo-ime--before-save))
      (cl-assert cancelled)
      (cl-assert (equal (buffer-string) "prefix:日本")))))

(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (insert "modified")
  (neo-ime--display (selected-window) "次" 0 [0])
  (neo-ime--clear)
  (cl-assert (buffer-modified-p)))

;; Cleanup must work even when a buffer becomes read-only during composition.
(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (neo-ime--display (selected-window) "次" 0 [0])
  (setq buffer-read-only t)
  (neo-ime--clear)
  (cl-assert (equal (buffer-string) "")))
;; Read-only preedit must cancel locally, not disable the global mode.
(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (setq buffer-read-only t)
  (let ((neo-ime-mode t)
        (neo-ime--frames (list (cons (selected-frame) -1)))
        (cancelled nil))
    (cl-letf (((symbol-function 'neo-ime-native-snapshot)
               (lambda (_) [20 "あ" 1 [0] t]))
              ((symbol-function 'neo-ime-native-cancel)
               (lambda (_) (setq cancelled t)))
              ((symbol-function 'neo-ime-native-detach) (lambda (_) t)))
      (neo-ime--poll)
      (cl-assert neo-ime-mode)
      (cl-assert cancelled)
      (cl-assert (equal (buffer-string) "")))))
(let ((text (neo-ime--candidate-text ["亜" "😀"] 10 9 100)))
  (cl-assert (equal (substring-no-properties text) " 1  亜 \n 2  😀 \n 11 / 100 "))
  (cl-assert (not (get-text-property 0 'face text)))
  (cl-assert (eq (get-text-property 8 'face text) 'highlight)))
(cl-assert (eq neo-ime-candidate-backend 'child-frame))
(cl-assert (not (featurep 'corfu)))
(defvar corfu-min-width 15)
(defvar corfu-max-width 100)
(with-temp-buffer
  (switch-to-buffer (current-buffer))
  (buffer-enable-undo)
  (set-buffer-modified-p nil)
  (neo-ime--display (selected-window) "亜" 1 [1])
  (let ((neo-ime-candidate-backend 'corfu) (shown nil) (hidden 0)
        (corfu-min-width 15) (corfu-max-width 100))
    (cl-letf (((symbol-function 'neo-ime--require-corfu) #'ignore)
              ((symbol-function 'posn-at-point) (lambda (&rest _) 'test-position))
              ((symbol-function 'corfu--popup-show)
               (lambda (&rest args) (setq shown args)))
              ((symbol-function 'corfu--popup-hide)
               (lambda () (cl-incf hidden))))
      (neo-ime--show-candidates (selected-frame)
                               [1 "亜" 1 [1] t ["亜" "あ"] 10 9 100])
      (cl-assert (equal (nth 3 shown) '("1  亜" "2  あ" "11 / 100")))
      (cl-assert (= (nth 4 shown) 1))
      (cl-assert (equal (buffer-substring-no-properties 1 2) "亜"))
      (cl-assert (not buffer-undo-list))
      (cl-assert (not (buffer-modified-p)))
      (neo-ime--show-candidates (selected-frame) [2 "亜" 1 [1] t [] 0 0 0])
      (cl-assert (= hidden 1))
      ;; A second cleanup must not hide an unrelated Corfu completion.
      (neo-ime--clear)
      (cl-assert (= hidden 1)))))
(cl-letf (((symbol-function 'require) (lambda (&rest _) nil)))
  (cl-assert (eq (car (condition-case err (neo-ime--require-corfu)
                       (user-error err))) 'user-error)))
(princ "NEO_IME_EL=PASS buffer-preedit undo-redo cancel modified utf16 stable-text read-only-mode-retained candidate-page corfu-backend\n")
